---
- name: Install locales
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - en_DK.UTF-8

# SSH keys

- name: Create /root/.ssh
  file: state=directory dest=/root/.ssh

- name: Install ssh public key
  copy: content="{{ ssh_pub_key }}\n" dest=/root/.ssh/id_rsa.pub
  when: ssh_pub_key|default(False)

- name: Install ssh private key
  copy: content="{{ ssh_priv_key }}\n" dest=/root/.ssh/id_rsa mode=600
  when: ssh_priv_key|default(False)

- name: Setup root authorized keys
  authorized_key:
    user: root
    exclusive: true
    key: "{% for key in root_authorized_keys %}{{ key }}\n{% endfor %}"
  when: root_authorized_keys|default(False)

- name: Allow root to ssh without password
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin without-password
  notify: Restart ssh

# Root .bashrc and .profile

- name: Install bashrc for root
  template: src=bashrc.j2 dest=/root/.bashrc

- name: Install profile for root
  copy: src=profile dest=/root/.profile

# Firewall

- name: Install ufw
  apt: name=ufw

- name: Allow ssh through firewall
  ufw: proto=tcp port=22 rule=allow

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny


- name: Install sudo
  apt: name=sudo

- name: Make sure we have pip
  apt: name=python-pip

- name: Install common SSL certificates
  apt: name=ca-certificates

- name: Install ntp
  apt: name=ntp

- name: Install debian-goodies
  apt: name=debian-goodies
